kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.clusterRole.name }}

{{- if or .Values.fetchEverything .Values.collectSecrets }}
rules:
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources:
      - '*'
{{- else }}
rules:
  - apiGroups:
      - '*'
    verbs:
      - get
      - list
      - watch
    resources:
      - clusterroles
      - ingresses
      - networkpolicies
      - daemonsets
      - deployments
      - replicasets
      - cronjobs
      - jobs
      - statefulsets
      - namespaces
      - nodes
      - events
      - services/status
      - services
      - serviceaccounts
      - replicationcontrollers
      - pods
      - persistentvolumeclaims
      - persistentvolumes
      - configmaps
      - endpoints
      - storageclasses
      - customresourcedefinitions
      - rollouts
      - rollouts/status
      - rollouts/finalizers
      - analysistemplates
      - clusteranalysistemplates
  - verbs:
      - get
      - list
      - watch
    apiGroups:
      - '*'
    resources: [ "secrets" ]
    resourceNames: [ "sh.helm.release.*" ]
  {{- end }}