apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
{{ if .Values.apiEndpoint }}
  endpoint: {{ quote .Values.apiEndpoint }}
{{ end }}
  collector.watchNamespace: default
  collector.ignoreNamespaces: |
    kube-system
  collector.overrideUniqueClusterId: {{ if .Values.overrideUniqueClusterId }}"true"{{ else }}"false"{{ end }}
  collector.resources: |
    {{ $resources := list "apiservices" "analysistemplates" "clusteranalysistemplates" "clusterroles" "clusterrolebindings" "configmaps" "controllerrevisions" "cronjobs" "csinodes" "customresourcedefinitions" "daemonsets" "deployments" "endpoints" "endpointslices" "flowschemas" "ingresses" "jobs" "leases" "namespaces" "networkpolicies" "nodes" "persistentvolumeclaims" "persistentvolumes" "pods" "priorityclasses" "prioritylevelconfigurations" "replicasets" "replicationcontrollers" "roles" "rolebindings" "rollouts" "rollouts/finalizers" "rollouts/status" "serviceaccounts" "services" "services/status" "statefulsets" "storageclasses" }}
    {{- range $i, $name := $resources }}
      {{- if has $name $.Values.removeTypes }}
        {{- continue -}}
      {{- end }}
      {{ $name -}}
    {{ end -}}
    {{- range $i, $name := $.Values.addTypes }}
      {{ $name -}}
    {{ end -}}
    {{- if and ($.Values.collectSecrets) (not (has "secrets" $.Values.addTypes)) }}
      secrets
    {{ end -}}
