apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{ .Release.Name }}-cronjob
spec:
  schedule: "{{ .Values.schedule }}"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: {{ .Values.serviceAccount.name }}
          containers:
            - name: {{ .Release.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              imagePullPolicy: {{ .Values.image.pullPolicy }}
              env:
                - name: INFRALIGHT_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: accessKey
                - name: INFRALIGHT_SECRET_KEY
                  valueFrom:
                    secretKeyRef:
                      name: {{ .Release.Name }}-credentials
                      key: secretKey
                - name: CLUSTER_ID
                  value: {{ .Values.clusterId }}
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
              resources:
                requests:
                  cpu: {{ .Values.resources.requests.cpu }}
                  memory: {{ .Values.resources.requests.memory }}
                limits:
                  cpu: {{ .Values.resources.limits.cpu }}
                  memory: {{ .Values.resources.limits.memory }}
          volumes:
            - name: config-volume
              configMap:
                name: {{ .Release.Name }}-config
          restartPolicy: OnFailure
