name: Build K8s Collector Image
on:
  workflow_dispatch:
    inputs:
      collectortag:
        description: 'Version Tag for the Collector Docker Image'
        required: true
        default: '1.0.0'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Get current time
      uses: gerred/actions/current-time@master
      id: current-time

    - name: Build and push image to prod
#      if: ${{ github.ref == 'refs/heads/main' }}
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          infralightio/k8s-collector:${{ github.event.inputs.collectortag }}
          infralightio/k8s-collector:latest
        labels: |
          org.opencontainers.image.created=${{ steps.current-time.outputs.time }}
          org.opencontainers.image.authors=Infralight
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.version=${{ github.event.inputs.collectortag }}

    - name: Slack Notification
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_COLOR: ${{ job.status }}
        SLACK_ICON: https://assets-global.website-files.com/5d514fd9493b0575f03520bd/5d8e0b39fd776a3c238e8753_icons8_infinity_large_filled_2.svg
        SLACK_MESSAGE: "K8s Collector image pushed to infralightio/k8s-collector:${{ github.event.inputs.collectortag }}"
        SLACK_TITLE: "K8s Collector image pushed to infralightio/k8s-collector:${{ github.event.inputs.collectortag }}"
        SLACK_USERNAME: cicdBot
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}